#!/bin/bash

# More cross-platform madness
# OSX's sed treats '-i' differently than GNU
sedi () {
    sed --version >/dev/null 2>&1 && sed -i -E "$@" || sed -i "" -E "$@"
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mkdir -p "$1-merged"

REMOVE="artifacts-"

for d in $(find $1 -mindepth 1 -type d ); do
  if find $d -maxdepth 1 -type f -name "*.ml" 2>/dev/null | grep -q .; then
    MERGED="$(echo "$d" | sed -e 's/[^A-Za-z0-9._-]/-/g').ml"
    MERGED=${MERGED#*$REMOVE}
    MERGED="$1-merged/$MERGED"

    cat $DIR/artifacts/preamble.txt $d/*.ml > "$MERGED"
    
    # Cleanup with sed 
    sedi 's/Z\.of_string "D\.[0-9]+?"/Z.of_string "0"/' "$MERGED"
    sedi 's/Z\.of_string ""/Z.of_string "0"/' "$MERGED"
    sedi 's/,  Inf/, infinity/' "$MERGED"
  fi
done
