#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Building c2ocaml plugin image..."
#/usr/bin/time -v -o $DIR/Logs/c2ocaml-image-build.time \
docker build \
  -t jjhenkel/c2ocaml \
  -f $DIR/Dockerfile $DIR \
  &> $DIR/logs/c2ocaml-image-build.log

STATUS=$?
if [ $STATUS -ne 0 ]; then
  echo "Plugin image failed to build."
  exit $STATUS
else
  echo "Image build complete!"
fi

echo "Populating volume with compiled so..."
docker rm build-c2ocaml &> /dev/null
#/usr/bin/time -v -o $DIR/Logs/c2ocaml-plugin-build.time \
docker run --name=build-c2ocaml \
  --volumes-from=c2ocaml-gcc7.2.0:ro \
  -v $DIR/plugin:/app/Lets/Transform/plugin \
  jjhenkel/c2ocaml \
  &> $DIR/logs/c2ocaml-plugin-build.log

STATUS=$?
if [ $STATUS -ne 0 ]; then
  echo "Plugin build failed."
  exit $STATUS
else
  echo "Volume populated!"
  exit 0
fi
